Areas/AdminBKPSDM/Controllers/PegawaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using New.Data;
using New.Models;
using FastReport.Utils;
using FastReport.Data;
using FastReport.Web;
using New.ViewModel;    
using System.Security.Claims;
using New.Utility;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using New.Repositories;

namespace New.Areas.AdminBKPSDM
{
    [Area("adminBKPSDM")]
    [Authorize(Roles = SD.AdminBKPSDM)]
    public class PegawaiController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PegawaiController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/Pegawai
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pegawai.ToListAsync());
        }

        public IActionResult Index2(int page = 1, string searchString = "",
           string sortOrder = "", string ErrorMsg = "")
        {

            if (ErrorMsg != "")
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }

            ViewData["NipSortParm"] = String.IsNullOrEmpty(sortOrder) ? "nipdesc" : "";
            ViewData["NamaSortParm"] = String.IsNullOrEmpty(sortOrder) ? "namadesc" : "";
            var p = new PegawaiList();

            var rowList = (from c in _context.Pegawai select c);

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                rowList = rowList.Where(c => c.Nama.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "nipdesc":
                    rowList = rowList.OrderBy(u => u.TglPensiun).ThenBy(u => u.NIP);
                    break;
                case "namadesc":
                    rowList = rowList.OrderBy(u => u.TglPensiun).ThenBy(u => u.Nama);
                    //rowList = rowList.OrderByDescending(u => u.TglPensiun).ThenBy(u => u.Nama);
                    break;
            }

            return View(rowList.GetPaged(page, 12));
        }


        // GET: SuperAdmin/Pegawai/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai
                .FirstOrDefaultAsync(m => m.NIP == id);
            if (pegawai == null)
            {
                return NotFound();
            }

            return View(pegawai);
        }

        // GET: SuperAdmin/Pegawai/Create
        public IActionResult Create(string ErrorMsg)
        {
            ViewBag.ErrorMsg = ErrorMsg;
            return View();
        }

        // POST: SuperAdmin/Pegawai/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NIP,Nama,GelarDepan,GelarBelakang,TempatLahir,TgLLahir,TglPensiun")] Pegawai pegawai)
        {
            if (ModelState.IsValid)
            {

                if (PegawaiExists(pegawai.NIP))
                {
                    //return RedirectToAction("Create", new { ErrorMsg = SD.msgErrPK });
                    ViewBag.ErrorMsg = SD.msgErrPKPegawai;
                    //return View(pegawai);
                    return View();

                }
                else
                {
                    _context.Add(pegawai);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Create", new { ErrorMsg = SD.msgSave });
                    //ViewBag.ErrorMsg = SD.msgSave;
                    //return View(pegawai);
                }
            }

            return View(pegawai);
        }

        // GET: SuperAdmin/Pegawai/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai.FindAsync(id);
            if (pegawai == null)
            {
                return NotFound();
            }
            return View(pegawai);
        }

        // POST: SuperAdmin/Pegawai/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("NIP,Nama,GelarDepan,GelarBelakang,TempatLahir,TgLLahir,TglPensiun")] Pegawai pegawai)
        {
            if (id != pegawai.NIP)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pegawai);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PegawaiExists(pegawai.NIP))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index2), new { ErrorMsg = SD.msgEdit });
            }
            return View(pegawai);
        }

        // GET: SuperAdmin/Pegawai/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai
                .FirstOrDefaultAsync(m => m.NIP == id);
            if (pegawai == null)
            {
                return NotFound();
            }

            return View(pegawai);
        }

        // POST: SuperAdmin/Pegawai/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Pegawai pegawai)
        {
            //var pegawai = await _context.Pegawai.FindAsync(id);
            //_context.Pegawai.Remove(pegawai);
            //await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index2), new { ErrorMsg = SD.msgDel });

            string ErrorReffLink = "";
            ErrorReffLink = CekReffLink(pegawai);
            if (ErrorReffLink != "")
            {
                ViewBag.ErrorReffLink = ErrorReffLink;
            }
            else
            {
                _context.Pegawai.Remove(pegawai);
                await _context.SaveChangesAsync(); 
                return RedirectToAction(nameof(Index2), new { ErrorMsg = SD.msgDel });
            }
            ViewBag.ErrorMsg = SD.msgErrDel;
            ViewBag.ErrorReffLink = ErrorReffLink;
            return View(pegawai);
        }

        private string CekReffLink(Pegawai pegawai)
        {
            string ErrorReffLink = "";

            //Cek Pegawai dengan PeriodeNIP
            var rList1 = _context.PeriodeNIP.Where(u => u.Nip == pegawai.NIP);

            if (rList1.Count() != 0) { ErrorReffLink += "Pegawai tidak bisa dihapus karena terdaftar di PeriodeNip" + "\n"; }

            return ErrorReffLink;
        }

        public async Task<IActionResult> Print()
        {
            var f = "~\\PegawaiBaru.frx";

            //var f = @"~\Reports\PegawaiBaru.frx";

            //string path = Server.MapPath("."); SqlServerReferenceOwnershipBuilderExtensions.Map HttpContext..Current.Request.ApplicationPath;

            RegisteredObjects.AddConnection(typeof(MsSqlDataConnection));
            MsSqlDataConnection sqlConnection = new MsSqlDataConnection();

            WebReport webReport = new WebReport();

            webReport.Report.SetParameterValue("IdUnitKerja", 12);
            webReport.Report.Load(f);
            ViewBag.WebReport = webReport;

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(await _context.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());

        }

        private bool PegawaiExists(string id)
        {
            return _context.Pegawai.Any(e => e.NIP == id);
        }
    }
}

Areas/SuperAdmin/Controllers/PegawaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using New.Data;
using New.Models;
using FastReport.Utils;
using FastReport.Data;
using FastReport.Web;
using New.ViewModel;
using System.Security.Claims;
using New.Utility;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using New.Repositories;

namespace New.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    [Authorize(Roles = SD.SuperAdmin)]
    public class PegawaiController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PegawaiController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/Pegawai
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pegawai.ToListAsync());
        }

        public IActionResult Index2(int page = 1, string searchString = "",
           string sortOrder = "", string ErrorMsg = "")
        {

            if (ErrorMsg != "")
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }

            ViewData["NipSortParm"] = String.IsNullOrEmpty(sortOrder) ? "nipdesc" : "";
            ViewData["NamaSortParm"] = String.IsNullOrEmpty(sortOrder) ? "namadesc" : "";
            var p = new PegawaiList();

            var rowList = (from c in _context.Pegawai select c);

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                rowList = rowList.Where(c => c.Nama.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "nipdesc":
                    rowList = rowList.OrderBy(u => u.TglPensiun).ThenBy(u => u.NIP);
                    break;
                case "namadesc":
                    rowList = rowList.OrderBy(u => u.TglPensiun).ThenBy(u => u.Nama);
                    //rowList = rowList.OrderByDescending(u => u.TglPensiun).ThenBy(u => u.Nama);
                    break;
            }

            return View(rowList.GetPaged(page, 12));
        }


        // GET: SuperAdmin/Pegawai/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai
                .FirstOrDefaultAsync(m => m.NIP == id);
            if (pegawai == null)
            {
                return NotFound();
            }

            return View(pegawai);
        }

        // GET: SuperAdmin/Pegawai/Create
        public IActionResult Create(string ErrorMsg)
        {
            ViewBag.ErrorMsg = ErrorMsg;
            return View();
        }

        // POST: SuperAdmin/Pegawai/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NIP,Nama,GelarDepan,GelarBelakang,TempatLahir,TgLLahir,TglPensiun")] Pegawai pegawai)
        {
            if (ModelState.IsValid)
            {

                if (PegawaiExists(pegawai.NIP))
                {
                    //return RedirectToAction("Create", new { ErrorMsg = SD.msgErrPK });
                    ViewBag.ErrorMsg = SD.msgErrPKPegawai;
                    //return View(pegawai);
                    return View();

                }
                else
                {
                    _context.Add(pegawai);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Create", new { ErrorMsg = SD.msgSave });
                    //ViewBag.ErrorMsg = SD.msgSave;
                    //return View(pegawai);
                }
            }

            return View(pegawai);
        }

        // GET: SuperAdmin/Pegawai/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai.FindAsync(id);
            if (pegawai == null)
            {
                return NotFound();
            }
            return View(pegawai);
        }

        // POST: SuperAdmin/Pegawai/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("NIP,Nama,GelarDepan,GelarBelakang,TempatLahir,TgLLahir,TglPensiun")] Pegawai pegawai)
        {
            if (id != pegawai.NIP)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pegawai);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PegawaiExists(pegawai.NIP))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index2), new { ErrorMsg = SD.msgEdit });
            }
            return View(pegawai);
        }

        // GET: SuperAdmin/Pegawai/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai
                .FirstOrDefaultAsync(m => m.NIP == id);
            if (pegawai == null)
            {
                return NotFound();
            }

            return View(pegawai);
        }

        // POST: SuperAdmin/Pegawai/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Pegawai pegawai)
        {
            //var pegawai = await _context.Pegawai.FindAsync(id);
            //_context.Pegawai.Remove(pegawai);
            //await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index2), new { ErrorMsg = SD.msgDel });

            string ErrorReffLink = "";
            ErrorReffLink = CekReffLink(pegawai);
            if (ErrorReffLink != "")
            {
                ViewBag.ErrorReffLink = ErrorReffLink;
            }
            else
            {
                _context.Pegawai.Remove(pegawai);
                await _context.SaveChangesAsync(); 
                return RedirectToAction(nameof(Index2), new { ErrorMsg = SD.msgDel });
            }
            ViewBag.ErrorMsg = SD.msgErrDel;
            ViewBag.ErrorReffLink = ErrorReffLink;
            return View(pegawai);
        }

        private string CekReffLink(Pegawai pegawai)
        {
            string ErrorReffLink = "";

            //Cek Pegawai dengan PeriodeNIP
            var rList1 = _context.PeriodeNIP.Where(u => u.Nip == pegawai.NIP);

            if (rList1.Count() != 0) { ErrorReffLink += "Pegawai tidak bisa dihapus karena terdaftar di PeriodeNip" + "\n"; }

            return ErrorReffLink;
        }

        public async Task<IActionResult> Print()
        {
            var f = "~\\PegawaiBaru.frx";

            //var f = @"~\Reports\PegawaiBaru.frx";

            //string path = Server.MapPath("."); SqlServerReferenceOwnershipBuilderExtensions.Map HttpContext..Current.Request.ApplicationPath;

            RegisteredObjects.AddConnection(typeof(MsSqlDataConnection));
            MsSqlDataConnection sqlConnection = new MsSqlDataConnection();

            WebReport webReport = new WebReport();

            webReport.Report.SetParameterValue("IdUnitKerja", 12);
            webReport.Report.Load(f);
            ViewBag.WebReport = webReport;

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(await _context.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());

        }

        private bool PegawaiExists(string id)
        {
            return _context.Pegawai.Any(e => e.NIP == id);
        }
    }
}

Areas/SuperAdmin/Views/Pegawai/Create.cshtml
@model New.Models.Pegawai

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<h4>Tambah Pegawai</h4>
<hr />


<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="NIP" class="control-label col-sm-2"></label>
        <div class="col-sm-4">
            <input asp-for="NIP" class="form-control" />
            <span asp-validation-for="NIP" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Nama" class="control-label col-sm-2"></label>
        <div class="col-sm-4">
            <input asp-for="Nama" class="form-control" />
            <span asp-validation-for="Nama" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="GelarDepan" class="control-label col-sm-2">Gelar Depan</label>
        <div class="col-sm-4">
            <input asp-for="GelarDepan" class="form-control" />
            <span asp-validation-for="GelarDepan" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="GelarBelakang" class="control-label col-sm-2">Gelar Belakang</label>
        <div class="col-sm-4">
            <input asp-for="GelarBelakang" class="form-control" />
            <span asp-validation-for="GelarBelakang" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="TempatLahir" class="control-label col-sm-2">Tempat Lahir</label>
        <div class="col-sm-4">
            <input asp-for="TempatLahir" class="form-control" />
            <span asp-validation-for="TempatLahir" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="TgLLahir" class="control-label col-sm-2">Tanggal Lahir</label>
        <div class="col-sm-4">
            <input asp-for="TgLLahir" class="form-control" asp-format="{0:MM/dd/yyyy}" />
            <span asp-validation-for="TgLLahir" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="TglPensiun" class="control-label col-sm-2">Tanggal Pensiun</label>
        <div class="col-sm-4">
            <input asp-for="TglPensiun" class="form-control" asp-format="{0:dd/MM/yyyy}"  />
            <span asp-validation-for="TgLLahir" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="control-label col-sm-2"></label>
        <div class="col-sm-4">
            <input type="submit" value="Simpan" class="btn btn-primary" />
            <a asp-action="Index2" class="btn btn-success">Kembali</a>
        </div>
    </div>
</form>

Areas/SuperAdmin/Views/Pegawai/Delete.cshtml
@model New.Models.Pegawai

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (ViewBag.ErrorReffLink != null)
{
    if (ViewBag.ErrorReffLink != "")
    {
        <div class="alert alert-info">
            <p>@ViewBag.ErrorReffLink</p>
        </div>
    }
}

<br />
<h4>Apakah anda yakin menghapus data pegawai ini?</h4>
<hr />

<div class="form-group row">

    <dt class="col-sm-2">
        Nama Pegawai
        @*@Html.DisplayNameFor(model => model.Nama)*@
    </dt>
    <dd class="col-sm-4 border-bottom">
        @Html.DisplayFor(model => model.Nama)
    </dd>
</div>

<div class="form-group row">
    <dt class="col-sm-2">
        Tempat Lahir
        @*@Html.DisplayNameFor(model => model.TempatLahir)*@
    </dt>
    <dd class="col-sm-4 border-bottom">
        @Html.DisplayFor(model => model.TempatLahir)
    </dd>
</div>

<div class="form-group row">
    <dt class="col-sm-2">
        Tgl Lahir
        @*@Html.DisplayNameFor(model => model.TgLLahir)*@
    </dt>
    <dd class="col-sm-4 border-bottom">
        @Html.DisplayFor(model => model.TgLLahir)
    </dd>
</div>

<div class="form-group row">
    <dt class="col-sm-2">
        Tgl Pensiun
        @*@Html.DisplayNameFor(model => model.TglPensiun )*@
    </dt>
    <dd class="col-sm-4 border-bottom">
        @Html.DisplayFor(model => model.TglPensiun)
    </dd>
</div>

<form asp-action="Delete">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="NIP" />
    <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col-sm-2">
            <input type="submit" value="Hapus" class="btn btn-danger" />
            <a class='btn btn-success' asp-action="Index2"> Kembali</a>
        </div>
    </div>
</form>

Areas/SuperAdmin/Views/Pegawai/Details.cshtml
@model New.Models.Pegawai

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Pegawai</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GelarDepan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GelarDepan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GelarBelakang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GelarBelakang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TempatLahir)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TempatLahir)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TgLLahir)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TgLLahir)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NIP">Edit</a>
    <a class='btn btn-outline-primary' asp-action="Index"><i class="fa fa-plus"></i> Kembali</a>
    
</div>

Areas/SuperAdmin/Views/Pegawai/Index2.cshtml
@model PagedResult<New.Models.Pegawai>
@using New.Models;
@{
    ViewData["Title"] = "Index";
}

@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);
}


<br />

@using (Html.BeginForm("Index2", "Pegawai", FormMethod.Get))
{
    <div class="col-12">
        <div class="row">
            <div class="col-sm-8">
                <h4>Daftar Pegawai </h4>
            </div>
            <div class="col-sm-4">
                <div class="nav justify-content-end">
                    <input id="Cari" type="text" class="form-control"
                     name="searchString" placeholder="Searching ...">
                </div>
            </div>
        </div>
    </div>
}

<div class="col-12">
    <br />
    <table class="table table-striped  table-sm">
        <thead class="thead-light">
            <tr>
                <th>
                    <a asp-action="Index2" asp-route-sortOrder="@ViewData["NipSortParm"]">NIP</a>
                </th>
                <th>
                    <a asp-action="Index2" asp-route-sortOrder="@ViewData["NamaSortParm"]">NAMA</a>
                </th>
                <th>
                    <div style="color:#007bff">TANGGAL LAHIR</div>
                </th>
                <th>
                    <div style="color:#007bff">TANGGAL PENSIUN</div>
                </th>
                <th>
                    <div class="nav justify-content-end">
                        <a class='btn btn-primary' asp-action="Create"><i class="fa fa-user-plus"></i></a>
                        &nbsp;
                        <a class='btn  btn-warning' asp-action="Print"><i class="fa fa-print"></i></a>
                        @*<a class='btn btn-primary' asp-action="Create"><i class="fa fa-plus"></i></a>
                            &nbsp;
                            <a class='btn  btn-warning' asp-action="Print"><i class="fa fa-print"></i></a>*@
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>


            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NIP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nama)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TgLLahir)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TglPensiun)
                    </td>
                    <td>
                        <div class="nav justify-content-end">
                            @*<a asp-action="Edit" asp-route-id="@item.NIP" class="btn btn-info">
                                    <i class="fa fa-pen-fancy"></i>
                                </a>
                                &nbsp;
                                <a asp-action="Delete" asp-area="SuperAdmin" asp-route-id="@item.NIP"
                                   class="btn btn-danger"><i class="fa fa-times"></i></a>*@

                            <a asp-action="Edit" asp-route-id="@item.NIP" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                            &nbsp;
                            <a asp-action="Delete" asp-route-id="@item.NIP" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></a>

                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@(await Component.InvokeAsync<PagerViewComponent>(Model))

Areas/SuperAdmin/Views/Pegawai/Print.cshtml
@{
    ViewData["Title"] = "Print";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await ViewBag.WebReport.Render();