Models/JamKerjaPola.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace New.Models
{
    public partial class JamKerjaPola
    {
        public JamKerjaPola()
        {
            PeriodeNIP = new HashSet<PeriodeNIP>();
            JamKerjaPolaDt = new HashSet<JamKerjaPolaDt>();

        }

        public int Id { get; set; }
        [Required]
        [StringLength(254)]
        public string Uraian { get; set; }

        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        public DateTime? ValidTill { get; set; }

        //[DataType(DataType.Time)]
        //[DisplayFormat(DataFormatString = "{0:hh\\:mm}")]

        //public TimeSpan? MasukA { get; set; }
        //[DataType(DataType.Time)]
        //[DisplayFormat(DataFormatString = "{0:hh\\:mm}")]
        //public TimeSpan? KeluarA { get; set; }
        //[DataType(DataType.Time)]
        //[DisplayFormat(DataFormatString = "{0:hh\\:mm}")]
        //public TimeSpan? MasukB { get; set; }
        //[DataType(DataType.Time)]
        //[DisplayFormat(DataFormatString = "{0:hh\\:mm}")]
        //public TimeSpan? KeluarB { get; set; }
        //public int? Jumlah { get; set; }
        //public bool Sen { get; set; }
        //public bool Sel { get; set; }
        //public bool Rab { get; set; }
        //public bool Kam { get; set; }
        //public bool Jum { get; set; }
        //public bool Sab { get; set; }
        //public bool Mgg { get; set; }


        [InverseProperty("IdJamKerjaPolaNavigation")]
        public virtual ICollection<PeriodeNIP> PeriodeNIP { get; set; }

        [InverseProperty("IdPolaNavigation")]
        public virtual ICollection<JamKerjaPolaDt> JamKerjaPolaDt { get; set; }
    }
}

Areas/SuperAdmin/Controllers/JamKerjaPolaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using New.Data;
using New.Models;
using New.Repositories;
using New.Utility;

namespace New.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    [Authorize(Roles = SD.SuperAdmin)]
    public class JamKerjaPolaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JamKerjaPolaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/JamKerjaPola
        public IActionResult Index(int page = 1, string searchString = "",
          string sortOrder = "")
        {

            ViewData["UraianParm"] = String.IsNullOrEmpty(sortOrder) ? "Uraiandesc" : "";
            ViewData["IdParm"] = String.IsNullOrEmpty(sortOrder) ? "Iddesc" : "";

            //var rowList = (from c in _context.JamKerjaPola
            //               select JamKerjaPola()
            //              );

            var rowList = _context.JamKerjaPola.AsQueryable(); //.AsEnumerable();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                rowList = rowList.Where(u => u.Uraian.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "Uraiandesc":
                    rowList = rowList.OrderByDescending(s => s.ValidTill).
                        ThenBy(s => s.Uraian);

                    break;
                case "Iddesc":
                    rowList = rowList.OrderByDescending(s => s.ValidTill).
                       ThenBy(s => s.Id);
                    break;
            }

            return View(rowList.GetPaged(page, 15));
        }


        // GET: SuperAdmin/JamKerjaPola/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jamKerjaPola = await _context.JamKerjaPola
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jamKerjaPola == null)
            {
                return NotFound();
            }

            return View(jamKerjaPola);
        }

        // GET: SuperAdmin/JamKerjaPola/Create
        public IActionResult Create()
        {
            var row = new JamKerjaPola
            {
                Id = NewId()
            };
            return View(row);
        }

        private int NewId()
        {
            int retVal = 0;
            var rList = _context.JamKerjaPola.OrderByDescending(u => u.Id).Take(1).FirstOrDefault();
            if (rList != null)
            {
                retVal = rList.Id + 1;
            }
            return retVal;
        }

        // POST: SuperAdmin/JamKerjaPola/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Uraian,ValidTill")]  JamKerjaPola jamKerjaPola)
        {

            if (ModelState.IsValid)
            {
                _context.Add(jamKerjaPola);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jamKerjaPola);
        }

        // GET: SuperAdmin/JamKerjaPola/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jamKerjaPola = await _context.JamKerjaPola.FindAsync(id);
            if (jamKerjaPola == null)
            {
                return NotFound();
            }
            return View(jamKerjaPola);
        }

        // POST: SuperAdmin/JamKerjaPola/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Uraian,ValidTill")] JamKerjaPola jamKerjaPola)
        {
            if (id != jamKerjaPola.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jamKerjaPola);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JamKerjaPolaExists(jamKerjaPola.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jamKerjaPola);
        }

        // GET: SuperAdmin/JamKerjaPola/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jamKerjaPola = await _context.JamKerjaPola
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jamKerjaPola == null)
            {
                return NotFound();
            }

            return View(jamKerjaPola);
        }

        // POST: SuperAdmin/JamKerjaPola/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jamKerjaPola = await _context.JamKerjaPola.FindAsync(id);
            _context.JamKerjaPola.Remove(jamKerjaPola);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JamKerjaPolaExists(int id)
        {
            return _context.JamKerjaPola.Any(e => e.Id == id);
        }
    }
}

Areas/SuperAdmin/Views/JamKerjaPola/Create.cshtml
@model New.Models.JamKerjaPola

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h4 class="col-9">Tambah Jam Kerja Pola</h4>
<hr />

<div class="col-6">
    <form asp-action="Create">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        @*<div class="form-group row">
            <label class="control-label col-sm-3"></label>
            <h5 class="col-9">//Jam Kerja Pola .(edit)</h5>
            <span asp-validation-for="Uraian" class="text-danger"></span>
        </div>*@

        <div class="form-group row">
            <label asp-for="Id" class="control-label col-sm-3"></label>
            <input asp-for="Id" class="form-control col-sm-9"  />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="Uraian" class="control-label col-sm-3"></label>
            <input asp-for="Uraian" class="form-control col-sm-9" />
            <span asp-validation-for="Uraian" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="ValidTill" class="control-label col-sm-3"></label>
            <input asp-for="ValidTill" class="form-control col-sm-9" />
            <span asp-validation-for="ValidTill" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label class="control-label col-sm-3"></label>
            <input type="submit" value="Simpan" class="form-control col-sm-2 btn btn-primary" />
            &nbsp;
            <a class="btn btn-success  col-sm-2" asp-action="Index">Kembali</a>
        </div>


    </form>




</div>

Areas/SuperAdmin/Views/JamKerjaPola/Delete.cshtml
@model New.Models.JamKerjaPola

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h4>Apakah anda yakin menghapus pola jam kerja ini?</h4>
<hr />

<div class="row">
    <div class="col-md-6">

        @*<div class="form-group row">
                <label class="control-label col-sm-3"></label>
                <div class="col-sm-9">
                    <h5>//Jam Kerja Pola (delete)</h5>
                </div>
            </div>*@

        @*Data Perorangan*@
        <div class="row">
            <label class="control-label col-sm-3">Id</label>
            <label class="control-label col-sm-9 border-bottom">@Model.Id</label>
        </div>

        <div class="row">
            <label class="control-label col-sm-3">Uraian</label>
            <label class="control-label col-sm-9 border-bottom">@Model.Uraian</label>
        </div>
        <div class="row">
            <label class="control-label col-sm-3">Valid Till</label>
            <label class="control-label col-sm-9 border-bottom">@Model.ValidTill.ToString()</label>
        </div>

        <form asp-action="Delete">
            <div class="form-group row">
                <label class="control-label col-sm-3"></label>
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Hapus" class="btn btn-danger" />
                &nbsp;
                <a class="btn btn-success" asp-action="Index">Kembali</a>
            </div>
        </form>

    </div>
</div>  

Areas/SuperAdmin/Views/JamKerjaPola/Details.cshtml
@model New.Models.JamKerjaPola

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>JamKerjaPola</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uraian)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uraian)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MasukA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MasukA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KeluarA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KeluarA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MasukB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MasukB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KeluarB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KeluarB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jumlah)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jumlah)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rab)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rab)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sab)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sab)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mgg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mgg)
        </dd>*@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/SuperAdmin/Views/JamKerjaPola/Edit.cshtml
@model New.Models.JamKerjaPola

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h4>Ubah Pola Jam Kerja</h4>
<hr />

<div class="col-6">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>        

        <div class="form-group row">
            <label asp-for="Id" class="control-label col-sm-3"></label>
            <input asp-for="Id" class="form-control col-sm-9" readonly />
            <span asp-validation-for="Uraian" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="Uraian" class="control-label col-sm-3"></label>
            <input asp-for="Uraian" class="form-control col-sm-9" />
            <span asp-validation-for="Uraian" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="ValidTill" class="control-label col-sm-3"></label>
            <input asp-for="ValidTill" class="form-control col-sm-9" />
            <span asp-validation-for="ValidTill" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label class="control-label col-sm-3"></label>
            <input type="submit" value="Simpan" class="btn btn-primary" />
            &nbsp;
            <a class="btn btn-success" asp-action="Index">Kembali</a>
        </div>
    </form>


</div>

Areas/SuperAdmin/Views/JamKerjaPola/Index.cshtml
@model PagedResult<New.Models.JamKerjaPola>

@using New.Models;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);
}

<br />


@using (Html.BeginForm("Index", "JamKerjaPola", FormMethod.Get))
{
    <div class="col-12">
        <div class="row">
            <div class="col-sm-8">
                <h4>Daftar Pola Jam Kerja </h4>
            </div>
            <div class="col-sm-4">
                <div class="nav justify-content-end">
                    <input id="Cari" type="text" class="form-control"
                           name="searchString" placeholder="Searching ...">
                </div>
            </div>
        </div>
    </div>
}

<br />
<div class="col-12">

    <table class="table table-striped table-sm ">
        <thead class="thead-light">
            <tr>
                <th>
                    <a asp-area="SuperAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["IdParm"]">ID</a>
                </th>
                <th>
                    <a asp-area="SuperAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["UraianParm"]">URAIAN</a>
                </th>
                <th>
                    <div style="color:#007bff">BERLAKU SAMPAI</div>
                </th>
                <th>
                    <div class="nav justify-content-end">
                        <a class='btn btn-primary' asp-action="Create"><i class="fa fa-plus"></i></a>
                        &nbsp;
                        <a class='btn  btn-warning' asp-action="Print"><i class="fa fa-print"></i> </a>
                    </div>
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Uraian)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ValidTill)
                    </td>

                    <td>
                        <div class="nav justify-content-end">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm"><i class="fa fa-edit"></i>
                            </a>
                            &nbsp;
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-times"></i>
                            </a>

                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@(await Component.InvokeAsync<PagerViewComponent>(Model))