Areas/SuperAdmin/Controllers/UserEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using New.Data;
using New.Models;

namespace New.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class UserEditController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserEditController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/UserEdit
        public IActionResult Index(int page = 1, string searchString = "#@s",
          string sortOrder = "", string ErrorMsg = "")
        {
            if (searchString != "#@s") ViewBag.searchString = searchString;
            
            ViewData["NipParm"] = String.IsNullOrEmpty(sortOrder) ? "NipDesc" : "";
            ViewData["NamaParm"] = String.IsNullOrEmpty(sortOrder) ? "NamaDesc" : "";

            var rowList = (from c in _context.ApplicationUser
                           .Where( u => u.Nama.Contains(searchString) || u.NIP.Contains(searchString))
                           select c);


            switch (sortOrder)
            {
                case "NipParm":
                    rowList = rowList.OrderBy(u => u.NIP);
                    break;
                case "NamaDesc":
                    rowList = rowList.OrderBy(u => u.Nama);
                    break;
            }

            if (ErrorMsg != "")
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }
            //;
            return View(rowList.GetPaged(page, 15));
        }

        // GET: SuperAdmin/UserEdit/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pegawai = await _context.Pegawai
                .FirstOrDefaultAsync(m => m.NIP == id);
            if (pegawai == null)
            {
                return NotFound();
            }

            return View(pegawai);
        }

        //// GET: SuperAdmin/UserEdit/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: SuperAdmin/UserEdit/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("NIP,Nama,GelarDepan,GelarBelakang,TempatLahir,TgLLahir,TglPensiun")] Pegawai pegawai)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(pegawai);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(pegawai);
        //}

        // GET: SuperAdmin/UserEdit/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uuser = _context.ApplicationUser.Where( u => u.NIP  ==  id).FirstOrDefault();
            if (uuser == null)
            {
                return NotFound();
            }
            return View(uuser);
        }

        // POST: SuperAdmin/UserEdit/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("NIP,Nama,UnitKerja")] ApplicationUser uuser)
        {
            if (id != uuser.NIP)
            {
                return NotFound();
            }

            var usersave = _context.ApplicationUser.Where(u => u.NIP == id).FirstOrDefault();
            usersave.UnitKerja = uuser.UnitKerja;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usersave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.ApplicationUser.Any( u => u.NIP == uuser.NIP))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { searchString = id });
            }
            return View(usersave);
        }

        // GET: SuperAdmin/UserEdit/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uuser = await _context.ApplicationUser
                .FirstOrDefaultAsync(m => m.NIP == id);
            if (uuser == null)
            {
                return NotFound();
            }

            return View(uuser);
        }

        // POST: SuperAdmin/UserEdit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string NIP)
        {
            var uuser = await _context.ApplicationUser.FirstOrDefaultAsync( u => u.NIP == NIP);
            _context.ApplicationUser.Remove(uuser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { searchString = NIP });
        }
         
    }
}

Areas/SuperAdmin/Views/UserEdit/Create.cshtml
@model New.Models.Pegawai

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Pegawai</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NIP" class="control-label"></label>
                <input asp-for="NIP" class="form-control" />
                <span asp-validation-for="NIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GelarDepan" class="control-label"></label>
                <input asp-for="GelarDepan" class="form-control" />
                <span asp-validation-for="GelarDepan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GelarBelakang" class="control-label"></label>
                <input asp-for="GelarBelakang" class="form-control" />
                <span asp-validation-for="GelarBelakang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TempatLahir" class="control-label"></label>
                <input asp-for="TempatLahir" class="form-control" />
                <span asp-validation-for="TempatLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TgLLahir" class="control-label"></label>
                <input asp-for="TgLLahir" class="form-control" />
                <span asp-validation-for="TgLLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TglPensiun" class="control-label"></label>
                <input asp-for="TglPensiun" class="form-control" />
                <span asp-validation-for="TglPensiun" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/SuperAdmin/Views/UserEdit/Delete.cshtml
@model New.Models.ApplicationUser

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<br />
<h4>Apakah anda yakin menghapus unit kerja ini?</h4>
<hr />

<div>
    @*<div class="row">
            <label class="col-2"></label>
            <div class="col-4">
                <h4>//  SKPD .(del)</h4>
            </div>
        </div>*@

    <div class="row">
        <label class="col-2">Nip</label>
        <label class="col-4 border-bottom">@Model.NIP</label>
    </div>

    <div class="row">
        <label class="col-2">Uraian</label>
        <label class="col-4 border-bottom">@Model.Nama</label>
    </div>

    <div class="row">
        <label class="col-2">Valid Till</label>
        <label class="col-4 border-bottom">@Model.UnitKerja</label>
    </div>


    <form asp-action="Delete">
        <div class="form-group row">

            <div class="col-sm-2"></div>
            <div class="col-sm-2">
                <input type="hidden" asp-for="NIP" />
                
                <input type="submit" value="Hapus" class="btn btn-danger" />
                <a class='btn btn-success' asp-action="Index">Kembali</a>
            </div>
        </div>
    </form>


</div>

Areas/SuperAdmin/Views/UserEdit/Details.cshtml
@model New.Models.Pegawai

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Pegawai</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GelarDepan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GelarDepan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GelarBelakang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GelarBelakang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TempatLahir)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TempatLahir)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TgLLahir)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TgLLahir)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TglPensiun)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TglPensiun)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NIP">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/SuperAdmin/Views/UserEdit/Edit.cshtml
@model New.Models.ApplicationUser

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<br />
<h4>Ubah user</h4>
<hr />

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="NIP" />

    <div class="form-group row ">
        <label class="col-2">Id</label>
        <input class="col-4 form-control" asp-for="NIP" readonly />
        <span asp-validation-for="NIP" class="text-danger"></span>
    </div>

    <div class="form-group row ">
        <label class="col-2">Nama</label>
        <input class="col-4 form-control" asp-for="Nama" />
    </div>

    <div class="form-group row">
        <label class="col-2">Unit Kerja</label>
        <input class="col-4 form-control" asp-for="UnitKerja" />
    </div>


    <div class="form-group row">
        <div class="col-sm-2"></div>
        <input type="submit" value="Simpan" class="btn btn-primary" />
        &nbsp;
        <a class='btn btn-success' asp-action="Index">Kembali</a>
    </div>
</form>

Areas/SuperAdmin/Views/UserEdit/Index.cshtml
@model PagedResult<New.Models.ApplicationUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);
}

<br />
@using (Html.BeginForm("Index", "UserEdit", FormMethod.Get))
{
    <div class="col-12">
        <div class="row">
            <div class="col-sm-8">
                <h4>Daftar User </h4>
            </div>
            <div class="col-sm-4">
                <div class="nav justify-content-end">
                    <input id="Cari" type="text" class="form-control"
                           name="searchString" placeholder="Searching ..."
                           value="@ViewBag.searchString">
                </div>
            </div>
        </div>
    </div>

}

<br />
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NipParm"]" asp-route-searchString=".," >NIP</a>
            </th>
            <th>
                <a asp-area="SuperAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["NamaParm"]" asp-route-searchString=".," >Nama</a>
            </th>
            <th>
                Unit Kerja
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Results)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NIP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitKerja)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.NIP">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.NIP">Details</a> |*@
                <a asp-action="Delete" asp-route-id="@item.NIP">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>



@(await Component.InvokeAsync<PagerViewComponent>(Model))