Models/HariKerjaStatus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace New.Models
{
    public partial class HariKerjaStatus
    {
        public HariKerjaStatus()
        {
            HariKerjaNip = new HashSet<HariKerjaNip>();
            HariKerja = new HashSet<HariKerja>();

        }

        public int Id { get; set; }
        [Required]
        [StringLength(254)]
        public string Uraian { get; set; }
        public bool Libur { get; set; }

        [InverseProperty("IdHariKerjaStatusNavigation")]
        public virtual ICollection<HariKerjaNip> HariKerjaNip { get; set; }

        [InverseProperty("IdLiburNavigation")]
        public virtual ICollection<HariKerja> HariKerja { get; set; }
    }
}

Areas/SuperAdmin/Controllers/HariKerjaStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using New.Data;
using New.Models;
using New.Repositories;
using New.Utility;

namespace New.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    [Authorize(Roles = SD.SuperAdmin)]
    public class HariKerjaStatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HariKerjaStatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/HariKerjaStatus
        public IActionResult Index(int page = 1, string searchString = "",
          string sortOrder = "")
        {

            ViewData["IdParm"] = String.IsNullOrEmpty(sortOrder) ? "IdDesc" : "";
            ViewData["UraianParm"] = String.IsNullOrEmpty(sortOrder) ? "UraianDesc" : "";
 

            var rowList = from c in _context.HariKerjaStatus 
                          select new HariKerjaStatus()
                          {
                              Id = c.Id,
                              Uraian = c.Uraian,
                              Libur = c.Libur
                          };

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                rowList = rowList.Where(c => c.Uraian.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "IdDesc":
                    rowList = rowList.OrderByDescending(s => s.Id);
                    break;
                case "UraianDesc":
                    rowList = rowList.OrderByDescending(s => s.Uraian);
                    break;
 
            }

            return View(rowList.GetPaged(page, 15));
        }

        // GET: SuperAdmin/HariKerjaStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hariKerjaStatus = await _context.HariKerjaStatus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hariKerjaStatus == null)
            {
                return NotFound();
            }

            return View(hariKerjaStatus);
        }

        // GET: SuperAdmin/HariKerjaStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SuperAdmin/HariKerjaStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Uraian,Libur")] HariKerjaStatus hariKerjaStatus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hariKerjaStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hariKerjaStatus);
        }

        // GET: SuperAdmin/HariKerjaStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hariKerjaStatus = await _context.HariKerjaStatus.FindAsync(id);
            if (hariKerjaStatus == null)
            {
                return NotFound();
            }
            return View(hariKerjaStatus);
        }

        // POST: SuperAdmin/HariKerjaStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Uraian,Libur")] HariKerjaStatus hariKerjaStatus)
        {
            if (id != hariKerjaStatus.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hariKerjaStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HariKerjaStatusExists(hariKerjaStatus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hariKerjaStatus);
        }

        // GET: SuperAdmin/HariKerjaStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hariKerjaStatus = await _context.HariKerjaStatus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hariKerjaStatus == null)
            {
                return NotFound();
            }

            return View(hariKerjaStatus);
        }

        // POST: SuperAdmin/HariKerjaStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hariKerjaStatus = await _context.HariKerjaStatus.FindAsync(id);
            _context.HariKerjaStatus.Remove(hariKerjaStatus);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HariKerjaStatusExists(int id)
        {
            return _context.HariKerjaStatus.Any(e => e.Id == id);
        }
    }
}

Areas/SuperAdmin/Views/HariKerjaStatus/Create.cshtml
@model New.Models.HariKerjaStatus

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Tambah Hari Kerja Status</h4>
<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="Id" class="control-label col-sm-1"></label>
        <div class="col-sm-4">
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Uraian" class="control-label col-sm-1"></label>
        <div class="col-sm-4">
            <input asp-for="Uraian" class="form-control" />
            <span asp-validation-for="Uraian" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Libur" class="control-label col-sm-1"></label>
        <div class="col-sm-4">
            <input asp-for="Libur" class="form-check-input"  />
            <span asp-validation-for="Libur" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-1"></label>
        <div class="col-sm-2">
            <input type="submit" value="Simpan" class="btn btn-primary" />
            <a class="btn btn-success" asp-action="Index">Kembali</a>
        </div>
    </div>
</form>

Areas/SuperAdmin/Views/HariKerjaStatus/Delete.cshtml
@model New.Models.HariKerjaStatus

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Apakah anda yakin menghapus data ini?</h4>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-1">
            Id
        </dt>
        <dd class="col-sm-4 border-bottom">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-1">
            Uraian
        </dt>
        <dd class="col-sm-4 border-bottom">
            @Html.DisplayFor(model => model.Uraian)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-1">
            Libur
        </dt>
        <dd class="col-sm-4 border-bottom">
            @Html.DisplayFor(model => model.Libur)
        </dd>
    </dl>
    <form asp-action="Delete">
        <div class="form-group row">
            <input type="hidden" asp-for="Id" />
            <div class="col-sm-1"></div>
            <div class="col-sm-2">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a class="btn btn-success" asp-action="Index">Kembali</a>
            </div>
        </div>
    </form>
</div>

Areas/SuperAdmin/Views/HariKerjaStatus/Details.cshtml
@model New.Models.HariKerjaStatus

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>HariKerjaStatus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uraian)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uraian)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Libur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Libur)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/SuperAdmin/Views/HariKerjaStatus/Edit.cshtml
@model New.Models.HariKerjaStatus

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Ubah Hari Kerja Status</h4>
<hr />

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group row">
        <label class="control-label col-sm-1">Uraian</label>
        <div class="col-sm-4">
            <input asp-for="Uraian" class="form-control" />
            <span asp-validation-for="Uraian" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="control-label col-sm-1">Status Libur</label>
        @*<label class="form-check-label ">*@
        <div class="col-sm-4">
            <input class="form-check-input" asp-for="Libur" /> @*@Html.DisplayNameFor(model => model.Libur)*@
        </div>
        @*</label>*@
    </div>
    <div class="form-group row">
        <div class="col-sm-1"></div>
        <div class="col-sm-4">
            <input type="submit" value="Simpan" class="btn btn-primary" />
            <a class="btn btn-success" asp-action="Index">Kembali</a>
        </div>
    </div>
</form>

Areas/SuperAdmin/Views/HariKerjaStatus/Index.cshtml
@model PagedResult<New.Models.HariKerjaStatus>
@using New.Models;
@{
    ViewData["Title"] = "Index";
}

@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);
}

</br>

@using (Html.BeginForm("Index", "HariKerjaStatus", FormMethod.Get))
{
    <div class="col-12">
        <div class="row">
            <div class="col-sm-8">
                <h4>Daftar Status Hari Kerja </h4>
            </div>
            <div class="col-sm-4">
                <div class="nav justify-content-end">
                    <input id="Cari" type="text" class="form-control"
                           name="searchString" placeholder="Searching ...">
                </div>
            </div>
        </div>
    </div>
}

<div class="col-12">
    </br>
    <table class="table table-striped table-sm table-bordered">
        <thead class="thead-light">

            <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["IdParm"]">ID</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["UraianParm"]">URAIAN</a>
                </th>
                <th>
                    <div style="color:#007bff">LIBUR</div>
                </th>
                <th>
                    <div class="nav justify-content-end">
                        <a class='btn btn-primary' asp-action="Create"><i class="fa fa-plus"></i></a>
                        &nbsp;
                        <a class='btn btn-warning' asp-action="Print"><i class="fa fa-print"></i></a>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Uraian)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Libur)
                    </td>
                    <td>
                        <div class="nav justify-content-end">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                            &nbsp;
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>